apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-sample
  labels:
    app: nginx-sample
  annotations:
    oci.oraclecloud.com/load-balancer-shape: "flexible"
spec:
  type: LoadBalancer
  selector:
    app: nginx-sample
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
