apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/devarintibhaskar/argocd-test.git"
    targetRevision: "master"
    path: "argocd-test"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "nginx-sample"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
